import { BlackJackGameInterface } from '../hooks/useBlackJackGameState';
import { Card } from './types';

export const cards: Card[] = [
  { isPrivate: false, symbol: 'AP', value: 'A' },
  { isPrivate: false, symbol: '2P', value: '2' },
  { isPrivate: false, symbol: '3P', value: '3' },
  { isPrivate: false, symbol: '4P', value: '4' },
  { isPrivate: false, symbol: '5P', value: '5' },
  { isPrivate: false, symbol: '6P', value: '6' },
  { isPrivate: false, symbol: '7P', value: '7' },
  { isPrivate: false, symbol: '8P', value: '8' },
  { isPrivate: false, symbol: '9P', value: '9' },
  { isPrivate: false, symbol: '10P', value: '10' },
  { isPrivate: false, symbol: 'JP', value: '10' },
  { isPrivate: false, symbol: 'QP', value: '10' },
  { isPrivate: false, symbol: 'KP', value: '10' },
  { isPrivate: false, symbol: 'AS', value: 'A' },
  { isPrivate: false, symbol: '2S', value: '2' },
  { isPrivate: false, symbol: '3S', value: '3' },
  { isPrivate: false, symbol: '4S', value: '4' },
  { isPrivate: false, symbol: '5S', value: '5' },
  { isPrivate: false, symbol: '6S', value: '6' },
  { isPrivate: false, symbol: '7S', value: '7' },
  { isPrivate: false, symbol: '8S', value: '8' },
  { isPrivate: false, symbol: '9S', value: '9' },
  { isPrivate: false, symbol: '10S', value: '10' },
  { isPrivate: false, symbol: 'JS', value: '10' },
  { isPrivate: false, symbol: 'QS', value: '10' },
  { isPrivate: false, symbol: 'KS', value: '10' },
  { isPrivate: false, symbol: 'AT', value: 'A' },
  { isPrivate: false, symbol: '2T', value: '2' },
  { isPrivate: false, symbol: '3T', value: '3' },
  { isPrivate: false, symbol: '4T', value: '4' },
  { isPrivate: false, symbol: '5T', value: '5' },
  { isPrivate: false, symbol: '6T', value: '6' },
  { isPrivate: false, symbol: '7T', value: '7' },
  { isPrivate: false, symbol: '8T', value: '8' },
  { isPrivate: false, symbol: '9T', value: '9' },
  { isPrivate: false, symbol: '10T', value: '10' },
  { isPrivate: false, symbol: 'JT', value: '10' },
  { isPrivate: false, symbol: 'QT', value: '10' },
  { isPrivate: false, symbol: 'KT', value: '10' },
  { isPrivate: false, symbol: 'AD', value: 'A' },
  { isPrivate: false, symbol: '2D', value: '2' },
  { isPrivate: false, symbol: '3D', value: '3' },
  { isPrivate: false, symbol: '4D', value: '4' },
  { isPrivate: false, symbol: '5D', value: '5' },
  { isPrivate: false, symbol: '6D', value: '6' },
  { isPrivate: false, symbol: '7D', value: '7' },
  { isPrivate: false, symbol: '8D', value: '8' },
  { isPrivate: false, symbol: '9D', value: '9' },
  { isPrivate: false, symbol: '10D', value: '10' },
  { isPrivate: false, symbol: 'JD', value: '10' },
  { isPrivate: false, symbol: 'QD', value: '10' },
  { isPrivate: false, symbol: 'KD', value: '10' }
];

export const initialData: BlackJackGameInterface = {
  gameRules: {
    soft17: true,
    decksNumber: 6,
    penetration: 0.75
  },
  setGameRules: () => undefined,
  gameRunning: false,
  setGameRunning: () => undefined,
  bettingStage: true,
  setBettingStage: () => undefined,
  splitHandStage: false,
  setSplitHandStage: () => undefined,
  bet: 0,
  setBet: () => undefined,
  balance: 1000,
  setBalance: () => undefined,
  players: [
    {
      seatTaken: false,
      isPlaying: false,
      hand: [],
      bet: 0,
      outcome: undefined,
      betOutcome: 0,
      canSplit: false,
      canDoubledown: true,
      canGetBlackJack: true,
      canSurrender: true,
      splitHands: [],
      playerName: 'player1'
    },
    {
      seatTaken: false,
      isPlaying: false,
      hand: [],
      bet: 0,
      betOutcome: 0,
      outcome: undefined,
      canSplit: false,
      canDoubledown: true,
      canGetBlackJack: true,
      canSurrender: true,
      splitHands: [],
      playerName: 'player2'
    },
    {
      seatTaken: true,
      isPlaying: false,
      hand: [],
      bet: 0,
      betOutcome: 0,
      outcome: undefined,
      canSplit: false,
      canDoubledown: true,
      canGetBlackJack: true,
      canSurrender: true,
      splitHands: [],
      playerName: 'player3'
    },
    {
      seatTaken: false,
      isPlaying: false,
      hand: [],
      bet: 0,
      betOutcome: 0,
      outcome: undefined,
      canSplit: false,
      canDoubledown: true,
      canGetBlackJack: true,
      canSurrender: true,
      splitHands: [],
      playerName: 'player4'
    },
    {
      seatTaken: false,
      isPlaying: false,
      hand: [],
      bet: 0,
      betOutcome: 0,
      outcome: undefined,
      canSplit: false,
      canDoubledown: true,
      canGetBlackJack: true,
      canSurrender: true,
      splitHands: [],
      playerName: 'player5'
    }
  ],
  setPlayers: () => undefined,
  handleSeatAvailability: () => undefined,
  handleSetupPlayers: () => undefined,
  handlePlayerBet: () => undefined,
  handlePlayerHit: () => undefined,
  handlePlayerStand: () => undefined,
  handlePlayerDoubledown: () => undefined,
  handlePlayerSplit: () => undefined,
  handlePlayerSurrender: () => undefined,
  dealer: [],
  setDealer: () => undefined,
  shoe: [],
  setShoe: () => undefined,
  dealtCardsAmount: 0,
  setDealtCardsAmount: () => undefined,
  penetrationReached: false,
  setPenetrationReached: () => undefined,
  isNewGame: true,
  setIsNewGame: () => undefined,
  dealSpeed: 0.5,
  gameData: [],
  setGameData: () => undefined,
  runningCount: 0,
  setRunningCount: () => undefined,
  setDealSpeed: () => undefined,
  dealCard: () => [],
  startGame: () => undefined,
  startDeal: () => undefined,
  countDealerValue: () => 0
};
